// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database_generated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GoogleUser struct {
	ID            pgtype.UUID
	GoogleID      string
	Email         string
	VerifiedEmail bool
	Name          pgtype.Text
	Picture       pgtype.Text
	Locale        pgtype.Text
}
